/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface AirdopMetadataInterface extends utils.Interface {
  functions: {
    "_airdoptime()": FunctionFragment;
    "_time(address)": FunctionFragment;
    "getAridop(address)": FunctionFragment;
    "getTimeStamp(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_airdoptime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "_time", values: [string]): string;
  encodeFunctionData(functionFragment: "getAridop", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getTimeStamp",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "_airdoptime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_time", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAridop", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTimeStamp",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AirdopMetadata extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AirdopMetadataInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _airdoptime(overrides?: CallOverrides): Promise<[BigNumber]>;

    _time(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getAridop(
      add: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getTimeStamp(
      add: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { time: BigNumber }>;
  };

  _airdoptime(overrides?: CallOverrides): Promise<BigNumber>;

  _time(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  getAridop(
    add: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getTimeStamp(add: string, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    _airdoptime(overrides?: CallOverrides): Promise<BigNumber>;

    _time(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getAridop(add: string, overrides?: CallOverrides): Promise<boolean>;

    getTimeStamp(add: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    _airdoptime(overrides?: CallOverrides): Promise<BigNumber>;

    _time(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getAridop(
      add: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getTimeStamp(add: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _airdoptime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _time(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAridop(
      add: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getTimeStamp(
      add: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
